name: Security Scan
on: [pull_request]
jobs:
  security-scan:
    runs-on: [self-hosted, laptop-armis]
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Scan Repository
        env:
          ARMIS_CLIENT_ID: ${{ secrets.ARMIS_CLIENT_ID }}
          ARMIS_CLIENT_SECRET: ${{ secrets.ARMIS_CLIENT_SECRET }}
        run: |
          ${{ vars.DLV }} exec ${{ vars.ARMIS_CLI }} \
          --headless \
          --log-dest=${{ vars.DLV_LOG }} \
          --listen=127.0.0.1:40000 \
          --api-version=2 \
          -- scan repo ${{ vars.DVNA_REPO }} \
          --format sarif \
          --fail-on '' > ${{ vars.DVNA_REPO }}/results.sarif
      - uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: ${{ vars.DVNA_REPO }}/results.sarif
